name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '11 6 * * *'

jobs:

  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      with:
        IMAGE_NAME: 'tailscale'
        TAG: 'lastest'
        BUILD_CONTEXT: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
